from app.schemas.clothing import (
    ClothingAnalyzeRequest,
    ClothingAnalyzeResponse,
    ClothingCategory,
    ClothingCreate,
    ClothingRead,
    ClothingThickness,
    ClothingUpdate,
)
from app.schemas.errors import ErrorDetail, ErrorResponse
from app.schemas.outfit import (
    OCCASION_OPTIONS,
    TARGET_STYLE_OPTIONS,
    OutfitReasoning,
    OutfitRecommendationRequest,
    OutfitRecommendationResponse,
    OutfitScoreBreakdown,
    RecommendationMeta,
    RecommendedOutfit,
    RecommendedOutfitItem,
    WeatherSourceByCity,
    WeatherSourceByLocation,
    WeatherSourceInput,
)
from app.schemas.weather import OutfitWeatherContext, WeatherData, WeatherLocation, WeatherProvider, WeatherSkillResponse

__all__ = [
    "ClothingAnalyzeRequest",
    "ClothingAnalyzeResponse",
    "ClothingCategory",
    "ClothingCreate",
    "ClothingRead",
    "ClothingThickness",
    "ClothingUpdate",
    "ErrorDetail",
    "ErrorResponse",
    "OCCASION_OPTIONS",
    "OutfitWeatherContext",
    "OutfitReasoning",
    "OutfitRecommendationRequest",
    "OutfitRecommendationResponse",
    "OutfitScoreBreakdown",
    "RecommendationMeta",
    "RecommendedOutfit",
    "RecommendedOutfitItem",
    "TARGET_STYLE_OPTIONS",
    "WeatherData",
    "WeatherLocation",
    "WeatherProvider",
    "WeatherSourceByCity",
    "WeatherSourceByLocation",
    "WeatherSourceInput",
    "WeatherSkillResponse",
]
